from typing import Any, Dict, List, Optional
from fastapi import APIRouter, Depends, HTTPException, Query, Response, status
from pydantic import BaseModel, Field
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.database import get_db, get_session_factory
from app.features.pipeline.service import pipeline_service

router = APIRouter()

class PipelineRunRequest(BaseModel):
    urls: List[str] = Field(..., min_items=1, description="List of seed URLs to crawl")
    threshold: int = Field(12, ge=3, le=25, description="SimHash threshold for deduplication")
    export_format: str = Field("parquet", description="Dataset export file format: 'json', 'csv', or 'parquet'")

class PipelineRunResponse(BaseModel):
    pipeline_id: str = Field(..., description="UUID of the started pipeline job")

class PipelineStatusResponse(BaseModel):
    pipeline_id: str = Field(..., description="Pipeline job UUID")
    status: str = Field(..., description="Status string: 'running', 'completed', 'failed', 'cancelled'")
    stage: str = Field(..., description="Current executing pipeline stage")
    progress: float = Field(..., description="Percentage progress of the pipeline run")
    collected_count: int = Field(..., description="Number of documents collected so far")
    error: Optional[str] = Field(None, description="Detailed error traceback if failed")

@router.post("/run", response_model=PipelineRunResponse, status_code=status.HTTP_202_ACCEPTED)
async def run_one_click_pipeline(
    payload: PipelineRunRequest,
    db_factory: Any = Depends(get_session_factory)
) -> Any:
    """
    Trigger the sequential One-Click Pipeline (Collect -> Clean -> Dedup -> Score -> Export).
    """
    pipeline_id = await pipeline_service.start_pipeline_job(
        db_factory=db_factory,
        urls=payload.urls,
        threshold=payload.threshold,
        export_format=payload.export_format
    )
    return {"pipeline_id": pipeline_id}

@router.get("/status/{pipeline_id}", response_model=PipelineStatusResponse, status_code=status.HTTP_200_OK)
async def get_pipeline_job_status(
    pipeline_id: str
) -> Any:
    """
    Retrieve current executing stage progress and stats logs for a pipeline.
    """
    status_data = pipeline_service.get_pipeline_status(pipeline_id)
    if not status_data:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Pipeline job '{pipeline_id}' not found."
        )
    return status_data

@router.post("/cancel/{pipeline_id}", status_code=status.HTTP_200_OK)
async def cancel_running_pipeline(
    pipeline_id: str
) -> Any:
    """
    Halt a running pipeline job immediately.
    """
    cancelled = await pipeline_service.cancel_pipeline(pipeline_id)
    if not cancelled:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=f"Pipeline job '{pipeline_id}' could not be cancelled (possibly finished or not found)."
        )
    return {"cancelled": True}

@router.get("/download/{pipeline_id}", status_code=status.HTTP_200_OK)
async def download_pipeline_export(
    pipeline_id: str
) -> Response:
    """
    Retrieve cached export package generated by a completed pipeline run.
    """
    pipeline_status = pipeline_service.get_pipeline_status(pipeline_id)
    if not pipeline_status:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Pipeline job '{pipeline_id}' not found."
        )
        
    if pipeline_status["status"] != "completed":
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=f"Pipeline job '{pipeline_id}' is not completed. Current status: {pipeline_status['status']}"
        )
        
    export_data = pipeline_service.get_pipeline_export(pipeline_id)
    if not export_data:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Export package not found for pipeline '{pipeline_id}'."
        )
        
    file_bytes, media_type, filename = export_data
    headers = {
        "Content-Disposition": f'attachment; filename="{filename}"'
    }
    
    return Response(
        content=file_bytes,
        media_type=media_type,
        headers=headers
    )
